
# Site settings
title: Simply Intellectual
description: A Blog by Leanna Faulk
baseurl: "/web1-sp" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "http://leannafaulk.github.io/Blog/" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
